### PR TITLE
Adding KEGG synonyms for TMAB

### PR DESCRIPTION
**Pull request by wkumler**
The workflow here seems to have caused the "quoting" issue that we were having before, so I'm submitting it as a PR so we can discuss how we want to handle this in the future.

1. Download "raw" Ingalls_Lab_Standards.csv using Chrome's "Save As" feature via Ctrl-S.
2. Save as *.csv file to Desktop
3. Open file using Excel
4. Find cell to change by using Ctrl-F in Excel
5. Make edits to cell by clicking on it and replacing the text in the formula bar. Format text as necessary (remove newlines) and hit Enter to save
6. Save file using Ctrl-S, again to Desktop
7. Upload file to GitHub using the "Add file -> Upload files" dialogue
8. Add commit message
9. Notice that the file now has 464 additions and 462 deletions, ugh

### CODE REVIEW

**Comment by wkumler** [comment]
All I really wanted to do was add KEGG's synonyms for TMAB: 
4-Trimethylammoniobutanoate; Butyro-betaine; gamma-Butyrobetaine

And maybe another name obtained from Sigma:
Deoxycarnitine

**Comment by R-Lionheart** [comment]
Ew 464 deletions + insertions? 

Thanks for ordering out the steps, that helps me understand the issues. Have you tried exporting it from excel as a csv and the uploading that to Github?

**Comment by wkumler** [comment]
Yep, because it's replacing every "line" of the CSV when it adds/removes quotes from everything. Looks like in this case it's removing the quote marks?

image

No difference as far as I can tell if I manually save as *.csv or simply hit Ctrl-S and say I'm sure to the dialogue box that warns me I might lose some formatting.


Although, I may have also introduced some new issues because I don't think I properly removed the newlines when I pasted it - the +/- shouldn't be different.

**Comment by wkumler** [comment]
Closing pull request to split the workflow into two pieces - first, removing quotes from all things that don't need them, then second, updating TMAB names

**Pull request closed without merging**
